go: 1.2
before_install: 
  - git clone https://github.com/coreos/etcd
  - cd etcd && bash build
  - bundle install --path .bundle
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
script: "bundle exec rake spec"
