before_install:
  - wget -c https://go.googlecode.com/files/go1.2.linux-amd64.tar.gz
  - tar -zxf go1.2.linux-amd64.tar.gz
  - git clone https://github.com/coreos/etcd
  - cd etcd && env GOROOT=../go PATH=$PATH:../go/bin bash build
  - bundle install --path .bundle
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
branches:
  only:
    - master
script: "bundle exec rake spec"
